//
//  ManageEventsViewController.swift
//  CLCSuperfan
//
//  Created by Brennan Reinhard on 4/18/25.
//

import UIKit
import MapKit

class ManageEventsViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate {
    
    // MARK: - outlets
    @IBOutlet weak var eventTable: UITableView!
    @IBOutlet weak var eventTitle: UITextField!
    @IBOutlet weak var eventCode: UITextField! // TODO: the secret "password" for redeeming events will eventually be autogenerated
    
    @IBOutlet weak var mapView: MKMapView!
    
    @IBOutlet weak var addButton: UIButton!
    
    @IBOutlet weak var datePicker: UIDatePicker!
    @IBOutlet weak var startTimePicker: UIDatePicker!
    @IBOutlet weak var stopTimePicker: UIDatePicker!
    
    // MARK: - variables
    private var events = [Event]()
    
    private var selectedCoordinate = CLLocationCoordinate2D(latitude: 42.23708, longitude: -88.32256) // set default coords to clc
    
    private var selectedEvent: Event?
    private var selectedIndex: Int?
    
    let geocoder = CLGeocoder()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // set table delegates
        eventTable.delegate = self
        eventTable.dataSource = self
        
        // configure refresh control for table
        let refreshControl = UIRefreshControl()
        refreshControl.addTarget(self, action: #selector(refresh), for: .valueChanged)
        
        eventTable.refreshControl = refreshControl
        
        // setup mapview
        setupMapView()
        refreshMapView()
        
        refresh()
    }
    
    // MARK: - helpers
    @objc func refresh() {
        NetworkManager.shared.request(api: EventAPI.all) { (result: Result<[Event], NetworkError>) in
            switch result {
            case .success(let events):
                self.events = events
                DispatchQueue.main.async {
                    self.eventTable.reloadData()
                    self.eventTable.refreshControl?.endRefreshing()
                }
                
            case .failure(let error):
                print("error fetching events: \(error)")
            }
        }
    }
    
    // TODO: maybe change to cllocation extension later?
    func coordinateToName(_ coordinate: CLLocationCoordinate2D, completion: @escaping (String) -> Void) {
        let location = coordinate.toCLLocation()
        geocoder.reverseGeocodeLocation(location) { placemarks, error in
            if let error = error {
                print("geocoding error: \(error)")
                completion("Unknown Location")
                return
            }
            
            if let placemark = placemarks?.first {
                // try to use placemark's name, but if it doesn't exist then use city name
                let name = placemark.name ?? placemark.locality ?? "Unnamed Location"
                completion(name)
            } else {
                completion("Unknown Location")
            }
        }
    }
    
    // sets up UITapGestureRecognizer on the mapview
    func setupMapView() {
        let gesture = UITapGestureRecognizer(target: self, action: #selector(handleMapTapGesture))
        gesture.delegate = self
        mapView.addGestureRecognizer(gesture)
    }
    
    // refreshes map annotations and camera
    func refreshMapView() {
        // remove all annotations from map
        mapView.removeAnnotations(mapView.annotations)
        
        // add new annotation displaying currently selected event location
        let annotation = MKPointAnnotation()
        annotation.coordinate = selectedCoordinate
        mapView.addAnnotation(annotation)
        
        // set map camera to 1000m x 1000m area around point
        mapView.setRegion(
            MKCoordinateRegion(
                center: annotation.coordinate,
                latitudinalMeters: 1000,
                longitudinalMeters: 1000),
            animated: true)
    }
    
    // resets mapview and textfields
    func resetFields() {
        self.eventTitle.text = ""
        self.eventCode.text = ""
        self.selectedCoordinate = CLLocationCoordinate2D(latitude: 42.23708, longitude: -88.32256)
    }
    
    // handles tap gesture on map
    @objc func handleMapTapGesture(gesture: UITapGestureRecognizer) {
        let touchPoint = gesture.location(in: mapView)
        let coordinate = mapView.convert(touchPoint, toCoordinateFrom: mapView)
        
        selectedCoordinate = coordinate
        refreshMapView()
    }
    
    // MARK: - actions
    // add/edit event action
    @IBAction func addEvent(_ sender: UIButton) {
        let day = Int(datePicker.date.timeIntervalSince1970)
        let start = Int(startTimePicker.date.timeIntervalSince1970)
        let stop = Int(stopTimePicker.date.timeIntervalSince1970)
        
        // edit mode
        if let event = selectedEvent, let index = selectedIndex {
            let newEvent = Event(
                id: event.id,
                name: eventTitle.text!,
                code: eventCode.text!,
                lat: selectedCoordinate.latitude,
                lon: selectedCoordinate.longitude,
                startTime: ,
                stopTime: Int(
            )
            
            // reset vc after editing
            eventTable.deselectRow(at: IndexPath(row: selectedIndex!, section: 0), animated: true)
            
            resetFields()
            self.selectedEvent = nil
            self.selectedIndex = nil

            NetworkManager.shared.request(api: EventAPI.updateEvent(id: event.id.uuidString, event: newEvent)) { (result: Result<Event, NetworkError>) in
                switch result {
                case .success:
                    print("edited event")
                case .failure(let error):
                    print("error editing event: \(error)")
                }
                
                DispatchQueue.main.async {
                    self.refresh()
                }
            }
        } else {
            // create mode
            // disregard the client-generated uuid, since server manages ids
            let newEvent = Event(id: UUID(), name: eventTitle.text!, code: eventCode.text!, lat: selectedCoordinate.latitude, lon: selectedCoordinate.longitude)
            
            NetworkManager.shared.request(api: EventAPI.createEvent(event: newEvent)) { (result: Result<Event, NetworkError>) in
                switch result {
                case .success:
                    print("created new event")
                case .failure(let error):
                    print("failed to create event, \(error)")
                }
                
                DispatchQueue.main.async {
                    self.refresh()
                }
            }
            
        }
        

    }
    
    
    
    
    // MARK: - delegate funcs
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        events.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let event = events[indexPath.row]
        
        let cell = eventTable.dequeueReusableCell(withIdentifier: "eventCell")!
        cell.textLabel!.text = event.name
        cell.detailTextLabel!.text = "Loading..."
        
        coordinateToName(CLLocationCoordinate2D(latitude: event.lat, longitude: event.lon)) { name in
            DispatchQueue.main.async {
                cell.detailTextLabel?.text = name
            }
        }
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        // set vc variables for selected row
        let event = events[indexPath.row]
        
        selectedEvent = event
        selectedIndex = indexPath.row
        
        
        // set text fields and map to be the selected row
        eventTitle.text = event.name
        eventCode.text = event.code
        
        selectedCoordinate = CLLocationCoordinate2D(latitude: event.lat, longitude: event.lon)
        refreshMapView()
        
        addButton.titleLabel!.text = "Edit"
    }
    
    // TODO: don't use deprecated functions
    func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]? {
        let deleteAction = UITableViewRowAction(style: .destructive, title: "Delete") { action, indexPath in
            NetworkManager.shared.request(api: EventAPI.deleteEvent(id: self.events[indexPath.row].id.uuidString)) { (result: Result<EmptyResponse, NetworkError>) in
                switch result {
                case .success(let deleted):
                    self.events.remove(at: indexPath.row)
                    
                    DispatchQueue.main.async {
                        self.eventTable.deleteRows(at: [indexPath], with: .automatic)
                    }
                    return
                case .failure(let error):
                    print("error deleting event, error: \(error)")
                }
            }
            
            self.selectedEvent = nil
            self.selectedIndex = nil
            
            DispatchQueue.main.async {
                self.resetFields()
                self.addButton.titleLabel!.text = "Add"
            }
            

        }
        
        return [deleteAction]
    }
    
    
    
}
// quick extension to convert cllocationcoordinate2d to cllocation
extension CLLocationCoordinate2D {
    func toCLLocation() -> CLLocation {
        return CLLocation(latitude: latitude, longitude: longitude)
    }
}
